replicaCount: 1

serviceAccount:
  create: false
  name: headlamp-readonly

clusterRoleBinding:
  create: false
  name: headlamp-readonly
  clusterRoleName: headlamp-readonly

config:
  inCluster: true
  extraArgs:
    - "-kubeconfig=/home/headlamp/.kube/config"

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: dashboard.k8sflow.space
      paths:
        - path: /
          type: Prefix
  tls:
    - secretName: ingress-tls
      hosts:
        - dashboard.k8sflow.space

volumes:
  - name: headlamp-kubeconfig
    secret:
      secretName: headlamp-kubeconfig

volumeMounts:
  - name: headlamp-kubeconfig
    mountPath: /home/headlamp/.kube/config
    subPath: config
    readOnly: true