installCRDs: true

replicaCount: 1

leaderElect: false
concurrent: 1

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

certController:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

serviceMonitor:
  enabled: false

grafanaDashboard:
  enabled: false

prometheus:
  enabled: false
