global:
  enabled: true
  tlsDisable: true

injector:
  enabled: false

server:
  enabled: true
  serviceAccount:
    create: true
    name: vault
  dev:
    enabled: false
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/vault/data"
      }
  ha:
    enabled: false
  dataStorage:
    enabled: true
    size: 2Gi
    mountPath: "/vault/data"
    accessMode: ReadWriteOnce
  auditStorage:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  service:
    enabled: true
    type: ClusterIP
    port: 8200
    targetPort: 8200

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations: {}
    hosts:
      - host: vault.k8sflow.space
        paths: ["/"]
    tls:
      - secretName: ingress-tls
        hosts:
          - vault.k8sflow.space

ui:
  enabled: true

csi:
  enabled: false
